### PR TITLE
Update to dogen 2.0.0

### PR DESCRIPTION
**Pull request by goldmann**
Additionally:

1. Remove the release key - not used/required
2. Change url to artifact in sources
3. Do not verify SSL - doesn't work with Akamai redirects
4. Change version to 1.0
5. Update envs section to follow new format

### CODE REVIEW

**Comment by lulf** [comment]
Looks good to me, thanks Marek!

**Comment by goldmann** [comment]
This should make it possible to build on our CI, right away.

**Comment by lulf** [comment]
Is that just for building the images or for running the tests as well?

**Comment by goldmann** [comment]
Building only, I'm not aware of any tests that you have. If you would add CTF (https://github.com/Containers-Testing-Framework/ctf-cli) tests, then these would be run too. Can you point me to your tests?

**Comment by lulf** [comment]
These tests are not for testing the containers, but the whole messaging-as-a-service deployed on openshift: https://github.com/EnMasseProject/systemtests/

Here's how we do CI upstream: https://github.com/EnMasseProject/enmasse/tree/master/documentation/ci

I'd like to be able to do something similar when building product images as well, as it would allow us to catch errors before tagging a non-working image. 

Since containers is our only way of deploying the service, we want to be able to test the images in a working deployment before we tag them with the target version.

Do you have any recommendations on how we could achieve that using the official build system?

**Pull request merged**
